# Generated by Django 3.1 on 2020-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='period3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(max_length=60)),
                ('efg', models.CharField(max_length=60)),
            ],
        ),
    ]
